version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    networks:
      - library-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "50051:50051"
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    environment:
      - GRPC_DNS_RESOLVER=ares
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - library-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:3000"
    environment:
      - WDS_SOCKET_PORT=0
    depends_on:
      - gateway
    networks:
      - library-network

  grpcui:
    image: fullstorydev/grpcui:latest
    container_name: grpcui
    command: ["-plaintext", "-port", "8081", "backend:50051"]
    ports:
      - "8081:8081"
    depends_on:
      - backend
    restart: always
    networks:
      - library-network


networks:
  library-network:
    driver: bridge

