# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryStub(object):
    """Service to manage the library
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/library.Library/CreateBook',
                request_serializer=library__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)
        self.GetBook = channel.unary_unary(
                '/library.Library/GetBook',
                request_serializer=library__pb2.GetBookRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/library.Library/ListBooks',
                request_serializer=library__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=library__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.Library/UpdateBook',
                request_serializer=library__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=library__pb2.Book.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/library.Library/DeleteBook',
                request_serializer=library__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library.Library/CreateMember',
                request_serializer=library__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.Member.FromString,
                _registered_method=True)
        self.GetMember = channel.unary_unary(
                '/library.Library/GetMember',
                request_serializer=library__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=library__pb2.Member.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/library.Library/ListMembers',
                request_serializer=library__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=library__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.Library/UpdateMember',
                request_serializer=library__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.Member.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/library.Library/DeleteMember',
                request_serializer=library__pb2.DeleteMemberRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.Library/BorrowBook',
                request_serializer=library__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=library__pb2.Borrowing.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.Library/ReturnBook',
                request_serializer=library__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=library__pb2.Borrowing.FromString,
                _registered_method=True)
        self.ListBorrowedBooks = channel.unary_unary(
                '/library.Library/ListBorrowedBooks',
                request_serializer=library__pb2.ListBorrowedBooksRequest.SerializeToString,
                response_deserializer=library__pb2.ListBorrowedBooksResponse.FromString,
                _registered_method=True)


class LibraryServicer(object):
    """Service to manage the library
    """

    def CreateBook(self, request, context):
        """Book RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Member RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Borrowing RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowedBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.CreateBookRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=library__pb2.GetBookRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=library__pb2.ListBooksRequest.FromString,
                    response_serializer=library__pb2.ListBooksResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=library__pb2.UpdateBookRequest.FromString,
                    response_serializer=library__pb2.Book.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=library__pb2.DeleteBookRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=library__pb2.CreateMemberRequest.FromString,
                    response_serializer=library__pb2.Member.SerializeToString,
            ),
            'GetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMember,
                    request_deserializer=library__pb2.GetMemberRequest.FromString,
                    response_serializer=library__pb2.Member.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=library__pb2.ListMembersRequest.FromString,
                    response_serializer=library__pb2.ListMembersResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=library__pb2.UpdateMemberRequest.FromString,
                    response_serializer=library__pb2.Member.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=library__pb2.DeleteMemberRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=library__pb2.BorrowBookRequest.FromString,
                    response_serializer=library__pb2.Borrowing.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=library__pb2.ReturnBookRequest.FromString,
                    response_serializer=library__pb2.Borrowing.SerializeToString,
            ),
            'ListBorrowedBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowedBooks,
                    request_deserializer=library__pb2.ListBorrowedBooksRequest.FromString,
                    response_serializer=library__pb2.ListBorrowedBooksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.Library', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.Library', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Library(object):
    """Service to manage the library
    """

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/CreateBook',
            library__pb2.CreateBookRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/GetBook',
            library__pb2.GetBookRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListBooks',
            library__pb2.ListBooksRequest.SerializeToString,
            library__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/UpdateBook',
            library__pb2.UpdateBookRequest.SerializeToString,
            library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/DeleteBook',
            library__pb2.DeleteBookRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/CreateMember',
            library__pb2.CreateMemberRequest.SerializeToString,
            library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/GetMember',
            library__pb2.GetMemberRequest.SerializeToString,
            library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListMembers',
            library__pb2.ListMembersRequest.SerializeToString,
            library__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/UpdateMember',
            library__pb2.UpdateMemberRequest.SerializeToString,
            library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/DeleteMember',
            library__pb2.DeleteMemberRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/BorrowBook',
            library__pb2.BorrowBookRequest.SerializeToString,
            library__pb2.Borrowing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ReturnBook',
            library__pb2.ReturnBookRequest.SerializeToString,
            library__pb2.Borrowing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowedBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListBorrowedBooks',
            library__pb2.ListBorrowedBooksRequest.SerializeToString,
            library__pb2.ListBorrowedBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
